using Factorio.Modding.Api.Attributes;
using System.CodeDom.Compiler;

namespace Factorio.Modding.Api.PrototypeStage.Enums;
                    

[GeneratedCode("Factorio.Modding.Api.CSharpSourceGenerator.Builders.CSharpClassBuilder", "unknown")]
public enum LinkedGameControlEnum
{
    [InLua("action-bar-select-page-1")]
    ActionBarSelectPage1,
	[InLua("action-bar-select-page-10")]
    ActionBarSelectPage10,
	[InLua("action-bar-select-page-2")]
    ActionBarSelectPage2,
	[InLua("action-bar-select-page-3")]
    ActionBarSelectPage3,
	[InLua("action-bar-select-page-4")]
    ActionBarSelectPage4,
	[InLua("action-bar-select-page-5")]
    ActionBarSelectPage5,
	[InLua("action-bar-select-page-6")]
    ActionBarSelectPage6,
	[InLua("action-bar-select-page-7")]
    ActionBarSelectPage7,
	[InLua("action-bar-select-page-8")]
    ActionBarSelectPage8,
	[InLua("action-bar-select-page-9")]
    ActionBarSelectPage9,
	[InLua("activate-tooltip")]
    ActivateTooltip,
	[InLua("add-station")]
    AddStation,
	[InLua("add-temporary-station")]
    AddTemporaryStation,
	[InLua("alt-zoom-in")]
    AltZoomIn,
	[InLua("alt-zoom-out")]
    AltZoomOut,
	[InLua("build")]
    Build,
	[InLua("build-ghost")]
    BuildGhost,
	[InLua("build-with-obstacle-avoidance")]
    BuildWithObstacleAvoidance,
	[InLua("cancel-craft")]
    CancelCraft,
	[InLua("cancel-craft-5")]
    CancelCraft5,
	[InLua("cancel-craft-all")]
    CancelCraftAll,
	[InLua("clear-cursor")]
    ClearCursor,
	[InLua("confirm-gui")]
    ConfirmGui,
	[InLua("confirm-message")]
    ConfirmMessage,
	[InLua("connect-train")]
    ConnectTrain,
	[InLua("controller-gui-crafting-tab")]
    ControllerGuiCraftingTab,
	[InLua("controller-gui-logistics-tab")]
    ControllerGuiLogisticsTab,
	[InLua("copy")]
    Copy,
	[InLua("copy-entity-settings")]
    CopyEntitySettings,
	[InLua("craft")]
    Craft,
	[InLua("craft-5")]
    Craft5,
	[InLua("craft-all")]
    CraftAll,
	[InLua("cursor-split")]
    CursorSplit,
	[InLua("cut")]
    Cut,
	[InLua("cycle-blueprint-backwards")]
    CycleBlueprintBackwards,
	[InLua("cycle-blueprint-forwards")]
    CycleBlueprintForwards,
	[InLua("cycle-clipboard-backwards")]
    CycleClipboardBackwards,
	[InLua("cycle-clipboard-forwards")]
    CycleClipboardForwards,
	[InLua("debug-reset-zoom")]
    DebugResetZoom,
	[InLua("debug-reset-zoom-2x")]
    DebugResetZoom2x,
	[InLua("debug-toggle-atlas-gui")]
    DebugToggleAtlasGui,
	[InLua("debug-toggle-basic")]
    DebugToggleBasic,
	[InLua("debug-toggle-debug-settings")]
    DebugToggleDebugSettings,
	[InLua("decrease-ui-scale")]
    DecreaseUiScale,
	[InLua("disconnect-train")]
    DisconnectTrain,
	[InLua("drag-map")]
    DragMap,
	[InLua("drop-cursor")]
    DropCursor,
	[InLua("editor-clone-item")]
    EditorCloneItem,
	[InLua("editor-delete-item")]
    EditorDeleteItem,
	[InLua("editor-next-variation")]
    EditorNextVariation,
	[InLua("editor-previous-variation")]
    EditorPreviousVariation,
	[InLua("editor-remove-scripting-object")]
    EditorRemoveScriptingObject,
	[InLua("editor-reset-speed")]
    EditorResetSpeed,
	[InLua("editor-set-clone-brush-destination")]
    EditorSetCloneBrushDestination,
	[InLua("editor-set-clone-brush-source")]
    EditorSetCloneBrushSource,
	[InLua("editor-speed-down")]
    EditorSpeedDown,
	[InLua("editor-speed-up")]
    EditorSpeedUp,
	[InLua("editor-switch-to-surface")]
    EditorSwitchToSurface,
	[InLua("editor-tick-once")]
    EditorTickOnce,
	[InLua("editor-toggle-pause")]
    EditorTogglePause,
	[InLua("fast-entity-split")]
    FastEntitySplit,
	[InLua("fast-entity-transfer")]
    FastEntityTransfer,
	[InLua("flip-blueprint-horizontal")]
    FlipBlueprintHorizontal,
	[InLua("flip-blueprint-vertical")]
    FlipBlueprintVertical,
	[InLua("focus-search")]
    FocusSearch,
	[InLua("increase-ui-scale")]
    IncreaseUiScale,
	[InLua("inventory-split")]
    InventorySplit,
	[InLua("inventory-transfer")]
    InventoryTransfer,
	[InLua("larger-terrain-building-area")]
    LargerTerrainBuildingArea,
	[InLua("logistic-networks")]
    LogisticNetworks,
	[InLua("mine")]
    Mine,
	[InLua("move-down")]
    MoveDown,
	[InLua("move-left")]
    MoveLeft,
	[InLua("move-right")]
    MoveRight,
	[InLua("move-up")]
    MoveUp,
	[InLua("next-active-quick-bar")]
    NextActiveQuickBar,
	[InLua("next-player-in-replay")]
    NextPlayerInReplay,
	[InLua("next-weapon")]
    NextWeapon,
	[InLua("open-character-gui")]
    OpenCharacterGui,
	[InLua("open-gui")]
    OpenGui,
	[InLua("open-item")]
    OpenItem,
	[InLua("open-prototype-explorer-gui")]
    OpenPrototypeExplorerGui,
	[InLua("open-prototypes-gui")]
    OpenPrototypesGui,
	[InLua("open-technology-gui")]
    OpenTechnologyGui,
	[InLua("open-trains-gui")]
    OpenTrainsGui,
	[InLua("order-to-follow")]
    OrderToFollow,
	[InLua("paste")]
    Paste,
	[InLua("paste-entity-settings")]
    PasteEntitySettings,
	[InLua("pause-game")]
    PauseGame,
	[InLua("pick-item")]
    PickItem,
	[InLua("pick-items")]
    PickItems,
	[InLua("place-in-chat")]
    PlaceInChat,
	[InLua("place-ping")]
    PlacePing,
	[InLua("previous-active-quick-bar")]
    PreviousActiveQuickBar,
	[InLua("previous-mod")]
    PreviousMod,
	[InLua("previous-technology")]
    PreviousTechnology,
	[InLua("production-statistics")]
    ProductionStatistics,
	[InLua("quick-bar-button-1")]
    QuickBarButton1,
	[InLua("quick-bar-button-1-secondary")]
    QuickBarButton1Secondary,
	[InLua("quick-bar-button-10")]
    QuickBarButton10,
	[InLua("quick-bar-button-10-secondary")]
    QuickBarButton10Secondary,
	[InLua("quick-bar-button-2")]
    QuickBarButton2,
	[InLua("quick-bar-button-2-secondary")]
    QuickBarButton2Secondary,
	[InLua("quick-bar-button-3")]
    QuickBarButton3,
	[InLua("quick-bar-button-3-secondary")]
    QuickBarButton3Secondary,
	[InLua("quick-bar-button-4")]
    QuickBarButton4,
	[InLua("quick-bar-button-4-secondary")]
    QuickBarButton4Secondary,
	[InLua("quick-bar-button-5")]
    QuickBarButton5,
	[InLua("quick-bar-button-5-secondary")]
    QuickBarButton5Secondary,
	[InLua("quick-bar-button-6")]
    QuickBarButton6,
	[InLua("quick-bar-button-6-secondary")]
    QuickBarButton6Secondary,
	[InLua("quick-bar-button-7")]
    QuickBarButton7,
	[InLua("quick-bar-button-7-secondary")]
    QuickBarButton7Secondary,
	[InLua("quick-bar-button-8")]
    QuickBarButton8,
	[InLua("quick-bar-button-8-secondary")]
    QuickBarButton8Secondary,
	[InLua("quick-bar-button-9")]
    QuickBarButton9,
	[InLua("quick-bar-button-9-secondary")]
    QuickBarButton9Secondary,
	[InLua("remove-pole-cables")]
    RemovePoleCables,
	[InLua("reset-ui-scale")]
    ResetUiScale,
	[InLua("reverse-rotate")]
    ReverseRotate,
	[InLua("reverse-select")]
    ReverseSelect,
	[InLua("alt-reverse-select")]
    AltReverseSelect,
	[InLua("rotate")]
    Rotate,
	[InLua("rotate-active-quick-bars")]
    RotateActiveQuickBars,
	[InLua("select-for-blueprint")]
    SelectForBlueprint,
	[InLua("select-for-cancel-deconstruct")]
    SelectForCancelDeconstruct,
	[InLua("shoot-enemy")]
    ShootEnemy,
	[InLua("shoot-selected")]
    ShootSelected,
	[InLua("show-info")]
    ShowInfo,
	[InLua("smaller-terrain-building-area")]
    SmallerTerrainBuildingArea,
	[InLua("smart-pipette")]
    SmartPipette,
	[InLua("stack-split")]
    StackSplit,
	[InLua("stack-transfer")]
    StackTransfer,
	[InLua("toggle-blueprint-library")]
    ToggleBlueprintLibrary,
	[InLua("toggle-console")]
    ToggleConsole,
	[InLua("toggle-driving")]
    ToggleDriving,
	[InLua("toggle-filter")]
    ToggleFilter,
	[InLua("toggle-gui-debug")]
    ToggleGuiDebug,
	[InLua("toggle-gui-glows")]
    ToggleGuiGlows,
	[InLua("toggle-gui-shadows")]
    ToggleGuiShadows,
	[InLua("toggle-gui-style-view")]
    ToggleGuiStyleView,
	[InLua("toggle-map")]
    ToggleMap,
	[InLua("toggle-menu")]
    ToggleMenu,
	[InLua("undo")]
    Undo,
	[InLua("zoom-in")]
    ZoomIn,
	[InLua("zoom-out")]
    ZoomOut
}