using Factorio.Modding.Api.Attributes;
using System.CodeDom.Compiler;

namespace Factorio.Modding.Api.PrototypeStage.Enums;
                    

[GeneratedCode("Factorio.Modding.Api.CSharpSourceGenerator.Builders.CSharpClassBuilder", "unknown")]
public enum RenderLayerEnum
{
    [InLua("water-tile")]
    WaterTile,
	[InLua("ground-tile")]
    GroundTile,
	[InLua("tile-transition")]
    TileTransition,
	[InLua("decals")]
    Decals,
	[InLua("lower-radius-visualization")]
    LowerRadiusVisualization,
	[InLua("radius-visualization")]
    RadiusVisualization,
	[InLua("transport-belt-integration")]
    TransportBeltIntegration,
	[InLua("resource")]
    Resource,
	[InLua("building-smoke")]
    BuildingSmoke,
	[InLua("decorative")]
    Decorative,
	[InLua("ground-patch")]
    GroundPatch,
	[InLua("ground-patch-higher")]
    GroundPatchHigher,
	[InLua("ground-patch-higher2")]
    GroundPatchHigher2,
	[InLua("remnants")]
    Remnants,
	[InLua("floor")]
    Floor,
	[InLua("transport-belt")]
    TransportBelt,
	[InLua("transport-belt-endings")]
    TransportBeltEndings,
	[InLua("transport-belt-circuit-connector")]
    TransportBeltCircuitConnector,
	[InLua("floor-mechanics-under-corpse")]
    FloorMechanicsUnderCorpse,
	[InLua("corpse")]
    Corpse,
	[InLua("floor-mechanics")]
    FloorMechanics,
	[InLua("item")]
    Item,
	[InLua("lower-object")]
    LowerObject,
	[InLua("lower-object-above-shadow")]
    LowerObjectAboveShadow,
	[InLua("object")]
    Object,
	[InLua("higher-object-under")]
    HigherObjectUnder,
	[InLua("higher-object-above")]
    HigherObjectAbove,
	[InLua("item-in-inserter-hand")]
    ItemInInserterHand,
	[InLua("wires")]
    Wires,
	[InLua("wires-above")]
    WiresAbove,
	[InLua("entity-info-icon")]
    EntityInfoIcon,
	[InLua("entity-info-icon-above")]
    EntityInfoIconAbove,
	[InLua("explosion")]
    Explosion,
	[InLua("projectile")]
    Projectile,
	[InLua("smoke")]
    Smoke,
	[InLua("air-object")]
    AirObject,
	[InLua("air-entity-info-icon")]
    AirEntityInfoIcon,
	[InLua("light-effect")]
    LightEffect,
	[InLua("selection-box")]
    SelectionBox,
	[InLua("higher-selection-box")]
    HigherSelectionBox,
	[InLua("collision-selection-box")]
    CollisionSelectionBox,
	[InLua("arrow")]
    Arrow,
	[InLua("cursor")]
    Cursor
}